version: "3.9"
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: app
      MYSQL_PASSWORD: app123
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 30

  app:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    env_file: .env
    ports:
      - "8080:8080"
    command: ["/bin/api"]

  migrate:
    image: migrate/migrate:v4.17.0
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./db/migrations:/migrations
    command:
      - "-path=/migrations"
      - "-database=mysql://app:app123@tcp(mysql:3306)/appdb?multiStatements=true"
      - "up"
    restart: "no"


volumes:
  dbdata:
